#ifndef CASTAWAY_TEST_MACROS_H
#define CASTAWAY_TEST_MACROS_H

#define TEST_ENEMY_SYMBOL 'E'
#define TEST_PASSIVE_SYMBOL 'P'
#define TEST_DEAD_SYMBOL 'D'

#define TEST_ENEMY_MAX_COUNT 5
#define TEST_ENEMY_MIN_COUNT 0
#define TEST_PASSIVE_MAX_COUNT 5
#define TEST_PASSIVE_MIN_COUNT 0

#define TEST_PASSIVE_IDLE_TIME 5

#endif //CASTAWAY_TEST_MACROS_H
