#ifndef CASTAWAY_MACROS_H
#define CASTAWAY_MACROS_H

// GAME MACROS
#define MAP_HEIGHT 40
#define MAP_WIDTH 70

#define PLAYER_SYMBOL '@'

// ====== TEST MACROS ========
#define TEST_TILE_SYMBOL '.'
#define TEST_ENEMY_SYMBOL 'E'
#define TEST_PASSIVE_SYMBOL 'P'
#define TEST_ENEMY_MAX_COUNT 3
#define TEST_ENEMY_MIN_COUNT 0
#define TEST_PASSIVE_MAX_COUNT 3
#define TEST_PASSIVE_MIN_COUNT 0
#define TEST_PASSIVE_IDLE_TIME 5

#endif //CASTAWAY_MACROS_H
