#ifndef CASTAWAY_MACROS_H
#define CASTAWAY_MACROS_H

// SCREEN
#define SCREEN_HEIGHT 50
#define SCREEN_WIDTH 100
#define MAP_HEIGHT 1000
#define MAP_WIDTH 1000

// ENTITY
#define PLAYER_SYMBOL '@'

// MAP TILES
#define PLAIN_GROUND_SYMBOL ' '
#define GRASS_SYMBOL_1 '\''
#define GRASS_SYMBOL_2 '\"'
#define GRASS_SYMBOL_3 ','
#define GRASS_SYMBOL_4 '`'
#define FLOWER_SYMBOL '*'
#define MOUNTAIN_OUTSIDE_SYMBOL 'X'
#define MOUNTAIN_INSIDE_SYMBOL '.'

// ======== TEST ========
#define TEST_ENEMY_SYMBOL 'E'
#define TEST_PASSIVE_SYMBOL 'P'
#define TEST_DEAD_SYMBOL 'D'

#define TEST_ENEMY_MAX_COUNT 5
#define TEST_ENEMY_MIN_COUNT 0
#define TEST_PASSIVE_MAX_COUNT 5
#define TEST_PASSIVE_MIN_COUNT 0

#define TEST_PASSIVE_IDLE_TIME 5

#endif //CASTAWAY_MACROS_H
